config/routes.rb
Rails.application.routes.draw do
  get 'students/delete'

  resources :student_apps
  get 'students/new'

  get 'students/edit'

  get 'students/show'

  get 'students/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student_app.rb
class StudentApp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/student_apps_controller.rb
class StudentAppsController < ApplicationController
  before_action :set_student_app, only: [:show, :edit, :update, :destroy]

  # GET /student_apps
  # GET /student_apps.json
  def index
    @student_apps = StudentApp.all
  end

  # GET /student_apps/1
  # GET /student_apps/1.json
  def show
  end

  # GET /student_apps/new
  def new
    @student_app = StudentApp.new
  end

  # GET /student_apps/1/edit
  def edit
  end

  # POST /student_apps
  # POST /student_apps.json
  def create
    @student_app = StudentApp.new(student_app_params)

    respond_to do |format|
      if @student_app.save
        format.html { redirect_to @student_app, notice: 'Student app was successfully created.' }
        format.json { render :show, status: :created, location: @student_app }
      else
        format.html { render :new }
        format.json { render json: @student_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_apps/1
  # PATCH/PUT /student_apps/1.json
  def update
    respond_to do |format|
      if @student_app.update(student_app_params)
        format.html { redirect_to @student_app, notice: 'Student app was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_app }
      else
        format.html { render :edit }
        format.json { render json: @student_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_apps/1
  # DELETE /student_apps/1.json
  def destroy
    @student_app.destroy
    respond_to do |format|
      format.html { redirect_to student_apps_url, notice: 'Student app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_app
      @student_app = StudentApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_app_params
      params.require(:student_app).permit(:firstname, :lastname, :category)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_apps_helper.rb
module StudentAppsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentAppCat217034853</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student_apps/_form.html.erb
<%= form_with(model: student_app, local: true) do |form| %>
  <% if student_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_app.errors.count, "error") %> prohibited this student_app from being saved:</h2>

      <ul>
      <% student_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :student_app_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :student_app_lastname %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :student_app_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_apps/edit.html.erb
<h1>Editing Student App</h1>

<%= render 'form', student_app: @student_app %>

<%= link_to 'Show', @student_app %> |
<%= link_to 'Back', student_apps_path %>

app/views/student_apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Apps</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_apps.each do |student_app| %>
      <tr>
        <td><%= student_app.firstname %></td>
        <td><%= student_app.lastname %></td>
        <td><%= student_app.category %></td>
        <td><%= link_to 'Show', student_app %></td>
        <td><%= link_to 'Edit', edit_student_app_path(student_app) %></td>
        <td><%= link_to 'Destroy', student_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student App', new_student_app_path %>

app/views/student_apps/new.html.erb
<h1>New Student App</h1>

<%= render 'form', student_app: @student_app %>

<%= link_to 'Back', student_apps_path %>

app/views/student_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @student_app.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student_app.lastname %>
</p>

<p>
  <strong>Category:</strong>
  <%= @student_app.category %>
</p>

<%= link_to 'Edit', edit_student_app_path(@student_app) %> |
<%= link_to 'Back', student_apps_path %>

app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>